config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.metadata.harvester:
      branch: master
      repo: https://bitbucket.org/cessda/cessda.metadata.harvester
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-chestnut-barb.sh
        container: qc.acc_frumpy-persimmon-akbash
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-apricot-insect.sh
        container: qc.doc_lousy-sapphire-chimpanzee
      bitbucket.org/cessda/cessda.metadata.harvester git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-plum-booby.sh
        container: qc.doc_shabby-dandelion-rattlesnake
      bitbucket.org/cessda/cessda.metadata.harvester markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-grey-monkey.sh
        container: qc.doc_foggy-taupe-spitz
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-puce-antelope.sh
        container: qc.lic_bumpy-ivory-sponge
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-eggplant-oyster.sh
        container: qc.sty_fuzzy-chestnut-peccary
      bitbucket.org/cessda/cessda.metadata.harvester jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-maroon-whale.sh
        container: qc.sty_hilly-mauve-oyster
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-harlequin-foxhound.sh
        container: qc.ver_greasy-copper-jellyfish
timeout: 1800
