config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.metadata.harvester:
      branch: 489-improve-harvester-sqa-rating
      repo: https://bitbucket.org/cessda/cessda.metadata.harvester
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-sepia-flounder.sh
        container: qc.acc_lanky-ecru-frise
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-tangerine-gar.sh
        container: qc.doc_gloppy-olivine-discus
      bitbucket.org/cessda/cessda.metadata.harvester git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-blue-spitz.sh
        container: qc.doc_thirsty-magenta-spitz
      bitbucket.org/cessda/cessda.metadata.harvester markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-gold-crane.sh
        container: qc.doc_wiggy-olivine-dolphin
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-fuchsia-fowl.sh
        container: qc.lic_sleazy-alizarin-sheepdog
  QC.Met:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-fuchsia-snake.sh
        container: qc.met_leaky-cream-squid
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.homely-corn-penguin.sh
        container: qc.sty_greasy-cream-argentino
      bitbucket.org/cessda/cessda.metadata.harvester jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-gamboge-corgi.sh
        container: qc.sty_silly-puce-balinese
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-orange-eleuth.sh
        container: qc.ver_squeaky-cyan-quokka
timeout: 1800
