config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.metadata.harvester:
      branch: master
      repo: https://bitbucket.org/cessda/cessda.metadata.harvester
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-pumpkin-uguisu.sh
        container: qc.acc_shaky-orange-mau
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-ivory-quokka.sh
        container: qc.doc_sleepy-orchid-hyena
      bitbucket.org/cessda/cessda.metadata.harvester git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-corn-snail.sh
        container: qc.doc_wimpy-puce-lionfish
      bitbucket.org/cessda/cessda.metadata.harvester markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-flax-heron.sh
        container: qc.doc_sleepy-brass-gopher
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-razzmatazz-donkey.sh
        container: qc.lic_pasty-cinnabar-fossa
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-tangerine-setter.sh
        container: qc.sty_droopy-magenta-forest
      bitbucket.org/cessda/cessda.metadata.harvester jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-amethyst-zonkey.sh
        container: qc.sty_tasty-malachite-cuscus
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-maroon-spaniel.sh
        container: qc.ver_crappy-tangerine-ferret
timeout: 1800
