config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.metadata.harvester:
      branch: master
      repo: https://bitbucket.org/cessda/cessda.metadata.harvester
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-charcoal-fish.sh
        container: qc.acc_gamy-aqua-moorhen
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-scarlet-insect.sh
        container: qc.doc_slaphappy-wisteria-fousek
      bitbucket.org/cessda/cessda.metadata.harvester git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-magenta-millipede.sh
        container: qc.doc_slimy-cinnamon-chicken
      bitbucket.org/cessda/cessda.metadata.harvester markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-ultramarine-leopard.sh
        container: qc.doc_surly-emerald-moth
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-amaranth-schnauzer.sh
        container: qc.lic_pasty-smalt-manatee
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-cream-bracke.sh
        container: qc.sty_silly-blue-gecko
      bitbucket.org/cessda/cessda.metadata.harvester jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-sangria-sponge.sh
        container: qc.sty_zippy-thistle-bulldog
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.metadata.harvester get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-malachite-hound.sh
        container: qc.ver_bumpy-pink-llama
timeout: 1800
